api:
  insecure: true
  dashboard: true

providers:
  file:
    directory: "/etc/traefik/"
    watch: true

log:
  level: INFO

entryPoints:
  web:
    address: ":8000"
  traefik:
    address: ":8080"

http:
  routers:
    odoo:
      rule: "Host(`localhost`)"
      service: "odoo"
    odoochat:
      rule: "Host(`localhost`) && PathPrefix(`/longpolling`)"
      service: odoochat
    quasar:
      rule: "Host(`localhost`) && PathPrefix(`/vue`, `/sockjs-node`)"
      service: quasar

  #  middlewares:
  #    quasar:
  #      stripPrefix:
  #        prefixes:
  #          - "/sockjs-node"
  #        forceSlash: false

  services:
    odoo:
      loadBalancer:
        servers:
          - url: "http://odoo13:13069"
    odoochat:
      loadBalancer:
        servers:
          - url: "http://odoo13:13899"
    quasar:
      loadBalancer:
        servers:
          - url: "http://quasar:9000"
